import {Inter, Poppins} from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import Layout from "@/components/Layout";
import Providers from "@/util/providers";

const poppins = Poppins({subsets: ["latin"], weight: ["400"]})
const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Edwin",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {

    return (
        <ClerkProvider frontendApi={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
            <html lang="en">
            <body className={poppins.className}>
            <Providers>
                <Layout>
                    {children}
                </Layout>
            </Providers>
            </body>
            </html>
        </ClerkProvider>
    );
}
